name: Staging CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Unit Test
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_USER_TOKEN: ${{ secrets.GH_TOKEN }}
      run: mvn --settings settings.xml test
    # Staging tag will be generated when commit is pushed to master, X.Y.Z-beta
    - name: Tagging
      id: tagging
      uses: anothrNick/github-tag-action@1.36.0
      env:
        RELEASE_BRANCHES: release
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
        PRERELEASE_SUFFIX: beta
    - name: Get ECR Login
      id: get_ecr_login
      run: echo ::set-output name=ecr_login::\"$(aws ecr get-login-password)\"
    - name: ECR Push
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_USER_TOKEN: ${{ secrets.GH_TOKEN }}
        ENVIRONMENT_ID: staging
      run: |
        mvn -U clean compile jib:build \
        --settings settings.xml \
        --file pom.xml \
        -Djib.from.auth.username=AWS \
        -Djib.from.auth.password=${{ steps.get_ecr_login.outputs.ecr_login }} \
        -Djib.to.auth.username=AWS \
        -Djib.to.auth.password=${{ steps.get_ecr_login.outputs.ecr_login }} \
        -Djib.to.tags=${{ steps.tagging.outputs.new_tag }}